import Foundation
enum MockData {
    static let credentials: [Credential] = [
        Credential(id:"c1", type:.education,    title:"B.Tech Computer Science",   description:"Bachelor of Technology, CS&E", issuerDid:"did:sov:IIT-Bombay-0xA1B2C3", subjectDid:Identity.mock.did, issuedAt:Date(timeIntervalSinceNow:-86400*365*4), expiresAt:nil,                                status:.active,  trustState:.verified, hash:"sha256:a1b2c3d4e5f678901234", signature:"sig:0xA1B2", isVerified:true,  rawJson:nil),
        Credential(id:"c2", type:.identity,     title:"Aadhaar Digital Identity",  description:"Government biometric identity", issuerDid:"did:sov:UIDAI-GOV-0xD4E5F6",  subjectDid:Identity.mock.did, issuedAt:Date(timeIntervalSinceNow:-86400*365*2), expiresAt:Date(timeIntervalSinceNow:86400*365*3), status:.active,  trustState:.verified, hash:"sha256:d4e5f6a7b8c9d0e1f2", signature:"sig:0xD4E5", isVerified:true,  rawJson:nil),
        Credential(id:"c3", type:.professional, title:"AWS Solutions Architect",   description:"Professional cloud certification", issuerDid:"did:sov:Amazon-AWS-0xG7H8I9", subjectDid:Identity.mock.did, issuedAt:Date(timeIntervalSinceNow:-86400*180),    expiresAt:Date(timeIntervalSinceNow:86400*365*2), status:.active,  trustState:.trusted,  hash:"sha256:g7h8i9j0k1l2m3n4o5", signature:"sig:0xG7H8", isVerified:true,  rawJson:nil),
        Credential(id:"c4", type:.membership,   title:"ACM Senior Member",         description:"Association for Computing Machinery", issuerDid:"did:sov:ACM-0xJ1K2L3",    subjectDid:Identity.mock.did, issuedAt:Date(timeIntervalSinceNow:-86400*90),     expiresAt:Date(timeIntervalSinceNow:86400*275),   status:.active,  trustState:.trusted,  hash:"sha256:j1k2l3m4n5o6p7q8r9", signature:"sig:0xJ1K2", isVerified:true,  rawJson:nil),
        Credential(id:"c5", type:.professional, title:"AI Safety Fundamentals",    description:"Anthropic AI Safety Certificate",    issuerDid:"did:sov:Anthropic-0xM4N5O6", subjectDid:Identity.mock.did, issuedAt:Date(timeIntervalSinceNow:-86400*30),     expiresAt:nil,                                status:.active,  trustState:.trusted,  hash:"sha256:m4n5o6p7q8r9s0t1u2", signature:"sig:0xM4N5", isVerified:true,  rawJson:nil),
    ]
    static let posts: [Post] = [
        Post(id:"p1", content:"The new RBI circular on digital lending mandates explicit digital consent from borrowers before accessing credit bureau data. This marks a significant shift in data governance for NBFCs.", author:PostAuthor(did:"did:sov:RBI-GOV-0xR1B2I3", displayName:"Reserve Bank of India", handle:"@rbi.official", avatarEmoji:"🏦", institution:"Reserve Bank of India", trustState:.verified, isVerified:true), sourceUrl:"https://rbi.org.in/circular/2025", sourceName:"RBI Official", publishedAt:Date(timeIntervalSinceNow:-3600), verificationStatus:.verifiedAuthor, trustState:.verified, claimCount:4, verifiedClaimCount:4, tags:["finance","regulation","RBI"], fraudAnalysis:nil),
        Post(id:"p2", content:"BREAKING: Major cryptocurrency exchange collapsed overnight. Reports claim $2.3 billion in customer funds unaccounted for. Investigations underway.", author:PostAuthor(did:"did:sov:unknown-0x999", displayName:"CryptoAlert24", handle:"@cryptoalert24", avatarEmoji:"📢", institution:nil, trustState:.suspicious, isVerified:false), sourceUrl:nil, sourceName:nil, publishedAt:Date(timeIntervalSinceNow:-7200), verificationStatus:.unverifiedAuthor, trustState:.suspicious, claimCount:3, verifiedClaimCount:0, tags:["crypto","breaking","unverified"], fraudAnalysis:FraudAnalysis(trustState:.suspicious, signals:[FraudSignal(id:.noSource, label:"No Source URL", severity:.high, detail:"Claim has no verifiable source link", remediation:"Check official exchange announcements"), FraudSignal(id:.unverifiedAuthor, label:"Unverified Author", severity:.medium, detail:"Author DID not in trusted registry", remediation:"Verify author credentials"), FraudSignal(id:.rapidPosting, label:"Rapid Posting", severity:.low, detail:"12 similar posts in past hour", remediation:nil)], riskScore:78, analysedAt:Date())),
        Post(id:"p3", content:"IIT Bombay announces new postgraduate program in Quantum Computing for 2025 batch. 40 total seats with 20% reserved for industry-sponsored candidates.", author:PostAuthor(did:"did:sov:IIT-Bombay-0xA1B2C3", displayName:"IIT Bombay", handle:"@iitbombay.official", avatarEmoji:"🎓", institution:"Indian Institute of Technology Bombay", trustState:.verified, isVerified:true), sourceUrl:"https://iitb.ac.in/admissions/2025", sourceName:"IIT Bombay Official", publishedAt:Date(timeIntervalSinceNow:-10800), verificationStatus:.verifiedAuthor, trustState:.verified, claimCount:5, verifiedClaimCount:5, tags:["education","IITBombay","quantum"], fraudAnalysis:nil),
    ]
    static let products: [Product] = [
        Product(id:"pr1", name:"MacBook Pro M4", brand:"Apple", serialNumber:"C02ZF4KHMD6T", manufacturerDid:"did:sov:Apple-Corp-0xAPPLE", status:.authentic, trustState:.verified, custodyChain:[CustodyCheckpoint(id:"cp1", location:"Zhengzhou, China", actor:"Foxconn", timestamp:Date(timeIntervalSinceNow:-86400*30), note:"Manufacturing complete"), CustodyCheckpoint(id:"cp2", location:"Shanghai Port", actor:"DHL Express", timestamp:Date(timeIntervalSinceNow:-86400*25), note:"Export customs cleared"), CustodyCheckpoint(id:"cp3", location:"Mumbai BDR", actor:"Apple India", timestamp:Date(timeIntervalSinceNow:-86400*10), note:"Distribution centre received")], manufacturedAt:Date(timeIntervalSinceNow:-86400*35), description:"Apple Silicon MacBook Pro with M4 chip", category:"Electronics"),
    ]
}
